language: python

python:
  - 2.7
  - 3.4

env:
  matrix:
  - DJANGO='django16' CMS='cms30'
  - DJANGO='django16' CMS='cms31'
  - DJANGO='django16' CMS='cms32'
  - DJANGO='django17' CMS='cms30'
  - DJANGO='django17' CMS='cms31'
  - DJANGO='django17' CMS='cms32'
  - DJANGO='django18' CMS='cms30'
  - DJANGO='django18' CMS='cms31'
  - DJANGO='django18' CMS='cms32'

matrix:
  allow_failures:
    - python: 2.7
      - env: DJANGO='django18' CMS='cms30'
      - env: DJANGO='django18' CMS='cms31'
      - env: DJANGO='django18' CMS='cms32'
    - python: 3.4
      - env: DJANGO='django18' CMS='cms30'
      - env: DJANGO='django18' CMS='cms31'
      - env: DJANGO='django18' CMS='cms32'

install:
  - pip install tox

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - tox -e"$TRAVIS_PYTHON_VERSION-$DJANGO-$CMS"
