language: python

env:
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=py34-django16
  - TOX_ENV=py34-django17

install:
  - pip install tox

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - tox -e $TOX_ENV
